include ../config.mk

# C source code files
C_FILES := src/mqtcccli.c \
           src/mqtcconn.c \
           src/mqtccthd.c \
           src/mqtcfcli.c \
           src/mqtcgctx.c \
           src/mqtcicli.c \
           src/mqtcncli.c \
           src/mqtcocli.c \
           src/mqtcpacd.c \
           src/mqtcpacr.c \
           src/mqtcpact.c \
           src/mqtcpdmp.c \
           src/mqtcping.c \
           src/mqtcpro2.c \
           src/mqtcpro3.c \
           src/mqtcpro4.c \
           src/mqtcpro5.c \
           src/mqtcpro6.c \
           src/mqtcpro7.c \
           src/mqtcpro9.c \
           src/mqtcprob.c \
           src/mqtcprod.c \
           src/mqtcpthd.c \
           src/mqtcptyp.c \
           src/mqtcpubb.c \
           src/mqtcpubf.c \
           src/mqtcpubl.c \
           src/mqtcrcli.c \
           src/mqtcrep4.c \
           src/mqtcrep5.c \
           src/mqtcsctx.c \
           src/mqtcsend.c \
           src/mqtcsnrc.c \
           src/mqtcspas.c \
           src/mqtcspro.c \
           src/mqtcssid.c \
           src/mqtcsubf.c \
           src/mqtcsubs.c \
           src/mqtcsuse.c \
           src/mqtcswmb.c \
           src/mqtcswms.c \
           src/mqtcswto.c \
           src/mqtctest.c \
           src/mqtcunsf.c \
           src/mqtcunss.c

# Assembler source files
A_FILES :=

include ../rules.mk
