include ../config.mk

# C source code files
C_FILES := src/mqttafre.c \
           src/mqttanew.c \
           src/mqttbye.c \
           src/mqttcli.c \
           src/mqttclif.c \
           src/mqttclin.c \
           src/mqttconn.c \
           src/mqttdump.c \
           src/mqttexec.c \
           src/mqttloop.c \
           src/mqttmain.c \
           src/mqttpars.c \
           src/mqttpub.c \
           src/strupper.c \
           src/test.c

# Assembler source files
A_FILES :=

include ../rules.mk
