include ../config.mk

# C source code files
C_FILES := src/utila2e.c \
           src/utilda2e.c \
           src/utilde2a.c \
           src/utile2a.c \
           src/utilfchr.c \
           src/utilgsht.c \
           src/utillend.c \
           src/utillene.c \
           src/utilmdup.c \
           src/utilntoa.c \
           src/utilonbs.c \
           src/utilprng.c \
           src/utilpsht.c \
           src/utilshwm.c \
           src/utilsocn.c \
           src/utilsocp.c \
           src/utilstru.c \
           src/utiltest.c \
           src/utilthwm.c \
           src/utiltopv.c

# Assembler source files
A_FILES :=

include ../rules.mk
