include ../config.mk

# C source code files
C_FILES := src/mqtbcfre.c \
           src/mqtbcnew.c \
           src/mqtbcons.c \
           src/mqtbconf.c \
           src/mqtbdt.c \
           src/mqtbinit.c \
           src/mqtbmain.c \
           src/mqtbpb.c \
           src/mqtbpbdm.c \
           src/mqtbpbf.c \
           src/mqtbpbv.c \
           src/mqtbpro1.c \
           src/mqtbpro3.c \
           src/mqtbpro4.c \
           src/mqtbpro5.c \
           src/mqtbpro6.c \
           src/mqtbpro7.c \
           src/mqtbpro8.c \
           src/mqtbpro9.c \
           src/mqtbproa.c \
           src/mqtbproc.c \
           src/mqtbproe.c \
           src/mqtbptyp.c \
           src/mqtbpubf.c \
           src/mqtbpubr.c \
           src/mqtbpubs.c \
           src/mqtbpubu.c \
           src/mqtbrep2.c \
           src/mqtbrep4.c \
           src/mqtbrep5.c \
           src/mqtbrep6.c \
           src/mqtbrep9.c \
           src/mqtbrepb.c \
           src/mqtbrepd.c \
           src/mqtbrets.c \
           src/mqtbscls.c \
           src/mqtbsend.c \
           src/mqtbsget.c \
           src/mqtbspro.c \
           src/mqtbsubt.c \
           src/mqtbterm.c \
           src/mqtbthdl.c \
           src/mqtbthdm.c \
           src/mqtbthdp.c \
           src/mqtbthds.c \
           src/mqtbthdw.c \
           src/mqtbtest.c \
           src/mqtbtopm.c \
           src/mqtbtops.c \
           src/mqtbtopv.c \
           src/mqtbunss.c \
           src/mqtbunst.c

# Assembler source files
A_FILES :=

include ../rules.mk
